# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
- job: nonSystemTest-jdk8
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/mdernst/ubuntu-for-randoop-jdk8
  steps:
  - bash: ./scripts/test-nonSystemTest.sh
- job: systemTest-jdk8
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/mdernst/ubuntu-for-randoop-jdk8
  steps:
  - bash: ./scripts/test-systemTest.sh
- job: nonSystemTest-jdk11
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/mdernst/ubuntu-for-randoop-jdk11
  steps:
  - bash: ./scripts/test-nonSystemTest.sh
- job: systemTest-jdk11
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/mdernst/ubuntu-for-randoop-jdk11
  steps:
  - bash: ./scripts/test-systemTest.sh
- job: misc
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/mdernst/ubuntu-for-randoop-jdkany
  steps:
  - bash: ./scripts/test-misc.sh
