version: 2.1

orbs:
  circle-compare-url: iynere/compare-url@1.2.0

jobs:
  nonSystemTest:

    docker:
      - image: mdernst/ubuntu-for-randoop-jdk8

    steps:

      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - checkout
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys:
            - gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-v2-{{ .Branch }}-
            - gradle-v2-

      - run: ./.circleci/nonSystemTest.sh

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}

  systemTest:

    docker:
      - image: mdernst/ubuntu-for-randoop-jdk8

    steps:

      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - checkout
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys:
            - gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-v2-{{ .Branch }}-
            - gradle-v2-

      - run:
          command: ./.circleci/systemTest.sh
          no_output_timeout: 20m

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}

  misc:

    docker:
      - image: mdernst/ubuntu-for-randoop-jdkany

    steps:

      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - checkout
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - circle-compare-url/reconstruct

      - restore_cache:
          keys:
            - gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-v2-{{ .Branch }}-
            - gradle-v2-

      # - run: ./.circleci/misc.sh
      - circle-compare-url/use:
          step-name: Desired step name to display on CircleCI
          attach-workspace: # set this to `true` if `reconstruct` was called as a job; default is `false`
          custom-logic: |
            ./.circleci/misc.sh

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}

workflows:
  build:
    jobs:
      # - nonSystemTest
      # - systemTest
      - misc
